model: 01-ai/Yi-Coder-1.5B
replica_id: 0
replica_resource_mapping: []
tokenizer: 01-ai/Yi-Coder-1.5B
tokenizer_mode: auto
trust_remote_code: true
download_dir: null
load_format: auto
dtype: float16
seed: 0
pipeline_parallel_size: 1
tensor_parallel_size: 4
placement_group: !!python/tuple
- null
block_size: 16
gpu_memory_utilization: 0.85
revision: null
scheduler_type: sarathi
max_model_len: null
max_num_seqs: 256
max_num_batched_tokens: null
chunk_size: null
enable_dynamic_chunking_schedule: false
low_chunk_size: null
high_chunk_size: null
chunk_schedule_max_tokens: null
chunk_schedule_stages: null
write_metrics: true
output_dir: .
wandb_project: null
wandb_sweep_id: null
wandb_run_id: null
wandb_group: null
wandb_run_name: null
enable_op_level_metrics: false
enable_cpu_op_level_metrics: false
enable_chrome_trace: false
enable_request_outputs: false
keep_individual_batch_metrics: false
attention_backend: flash_attention
strategy: !!python/object/apply:sarathi.config.Mode
- 1
time: null
required_blocks: null
pages_per_block: null
engine_type: old
original_gpu_count: null
drain_strategy: null
drain_timeout: null
kickout_strategy: null
selection_policy: null
serving_strategy: null
reschedule_policy: null
